inherit_gem:
  theforeman-rubocop:
    - strictest.yml
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - '*.spec'
    - 'doc/plugins/**'
    - 'locale/**'
    - 'vendor/bundle/**/*'  # necessary to make github actions linting work, see https://github.com/rubocop/rubocop/issues/9832

