require:
  - rubocop-rails

# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.2
  Exclude:
    - '*.spec'
    - 'doc/plugins/**'
    - 'locale/**'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
  SupportedStyles:
    - ruby19
    - hash_rockets

Metrics/LineLength:
  Max: 190

# Offense count: 21
# Configuration parameters: CountComments.
Metrics/ModuleLength:
    Max: 400

Naming/MethodName:
  Exclude:
    - 'app/models/concerns/orchestration/*.rb'

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
