inherit_gem:
  theforeman-rubocop:
    - strict.yml
    #- default.yml

# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'foreman_scc_manager.gemspec'

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Layout/LineLength:
  Max: 190

Layout/TrailingEmptyLines:
  Exclude:
    - 'locale/action_names.rb'

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 400

Style/WordArray:
  EnforcedStyle: brackets

Style/StringLiterals:
  Exclude:
    - 'locale/action_names.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false
