language: ruby
rvm:
  - 2.5
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - cd foreman
  - echo "gemspec :path => '../foreman_scc_manager'" > bundler.d/foreman_scc_manager.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - ln -s database.yml.example config/database.yml
  - bundle install --jobs=3 --retry=3 --without journald development postgresql mysql2 console
script:
  - bundle exec rubocop ../foreman_scc_manager
env:
  global:
    - TESTOPTS=-v
  matrix:
    - FOREMAN_CORE_BRANCH=1.22-stable KATELLO_CORE_BRANCH=KATELLO-3.12
    - FOREMAN_CORE_BRANCH=1.23-stable KATELLO_CORE_BRANCH=KATELLO-3.13
    - FOREMAN_CORE_BRANCH=1.24-stable KATELLO_CORE_BRANCH=KATELLO-3.14
addons:
  apt:
    packages:
    - nodejs
    - git
    - libsqlite3-dev
    - zlib1g-dev
    - libvirt-dev
