export const SCCPRODUCTPAGE_SUMMARY_MODAL_ID = 'SCCTreePickerForemanModal';
export const SCCPRODUCTPAGE_SUBSCRIBE = 'SCCPRODUCTPAGE_SUBSCRIBE';
export const SCCPRODUCTPAGE_SCCPRODUCTS = {
  key: 'SCCPRODUCTPAGE_GET_PRODUCTS',
};
