name: JavaScript Testing
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'webpack/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/js_tests.yml'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: JavaScript
    uses: theforeman/actions/.github/workflows/foreman_plugin_js.yml@v0
    with:
      plugin: foreman_scc_manager
