---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    # Pattern matched against refs/tags
    tags: ['**']

jobs:
  release:
    name: Release gem
    uses: theforeman/actions/.github/workflows/release-gem.yml@v0
    with:
      allowed_owner: ATIX-AG
    secrets:
      api_key: ${{ secrets.RUBYGEM_API_KEY }}
