name: Rubocop
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install libyaml-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: |
          gem install rubocop -v 0.89
          gem install rubocop-rails -v 2.8.1
      - name: Execute rubocop
        run: |
          rubocop
