name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    working-directory: /projects/foreman

jobs:
  test_ruby:
    defaults:
      run:
        working-directory: /projects/foreman
    env:
      PGHOST: postgres
      PGUSER: foreman
      PGPASS: foreman
      RAILS_ENV: test
      host: postgres
      WORKDIR: /projects/foreman
      BUNDLE_PATH: vendor/bundle
      GIT_COMMITTER_NAME: "gh_actions"
      GIT_COMMITTER_EMAIL: "gh_actions@rh_cloud.foreman"
    strategy:
      fail-fast: false
      matrix:
        foreman_version: [2_5, 3_1]

    runs-on: ubuntu-latest
    container:
      image: quay.io/shimshtein/tfm_plugin_test:foreman_${{ matrix.foreman_version }}

    services:
      postgres:
        image: quay.io/jomitsch/postgres-with-evr
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: foreman
          POSTGRES_PASSWORD: foreman

    steps:
      - name: Checkout foreman_scc_manager repo
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/projects/foreman_scc_manager
      - name: Fix git config
        run: |
          cp -Rf $GITHUB_WORKSPACE/projects/foreman_scc_manager /projects/
          cd /projects/foreman
          echo "gemspec :path => '../foreman_scc_manager'" > bundler.d/foreman_scc_manager.local.rb
          /usr/bin/entrypoint.sh git config --global user.name $GIT_COMMITTER_NAME
          /usr/bin/entrypoint.sh git config --global user.email $GIT_COMMITTER_EMAIL
      - name: remove foreman_rh_cloud and dependencies
        working-directory: /projects/foreman
        run: |
          rm bundler.d/foreman_rh_cloud.local.rb
          rm bundler.d/foreman_remote_execution.local.rb
      - name: remove foremen tasks dependency for Foreman 2.5
        working-directory: /projects/foreman
        if: ${{ matrix.foreman_version == '2_5' }}
        run: |
          rm bundler.d/foreman-tasks.local.rb
      - name: Run tests suite
        run: |
          cd /projects/foreman
          ls -al /usr/bin
          /usr/bin/entrypoint.sh chmod +rx /usr/bin/run_tests.sh
          /usr/bin/entrypoint.sh touch /usr/bin/setup_env.sh
          /usr/bin/entrypoint.sh chmod +rx /usr/bin/setup_env.sh
          /usr/bin/entrypoint.sh head -n -10 /usr/bin/run_tests.sh > /usr/bin/setup_env.sh
          /usr/bin/entrypoint.sh /usr/bin/setup_env.sh
      - name: Run Scc manager tests
        working-directory: /projects/foreman
        run: |
          /usr/bin/entrypoint.sh bundle exec rake test:foreman_scc_manager
          /usr/bin/entrypoint.sh bundle exec rake test TEST="test/unit/foreman/access_permissions_test.rb"
